### ISSUE TITLE
clhs.lisp.se is down

### ISSUE THREAD

**Issue by Hexstream** [Lisp-se/www.lisp.se#1]
Hello,

As you may know, clhs.lisp.se is currently down (`NXDOMAIN`). This breaks several thousands of links.

What's the status on this? Is it ever coming back?

It would be best if it at least redirected everything towards the official CLHS location.

(Honestly I had been worrying ever since the beginning that `clhs.lisp.se` would break one day, instead preferring the official location...)

**Comment by larsbrinkhoff** [comment]
The server that hosts clhs.lisp.se goes up and down occasionally.  Right now it's back up.  I'm not an admin on the server, so it's a bit out of my hands.

**Comment by larsbrinkhoff** [comment]
And now it's down again.

**Comment by Hexstream** [comment]
Well, seems to work now. Thanks.
